### ISSUE TITLE
Interested in full project

### ISSUE THREAD

**Issue by Mult1Hunter** [Henridv/laravel-booking#4]
Hello there!

I am looking for simple channel manager and I found your project. I know Laravel a bit but I struggle to get it up and runing completely. Looks like there are couple of key components missing. Registration form (view to be exact), home (view) etc.

Would you be willing to share last version of this project with me in return for compensation?

Let me know.

**Comment by Henridv** [comment]
Hi

This is the full project. Can you share, in more detail, which issues you are running into?

**Comment by Mult1Hunter** [comment]
Hi. Thanks for feedback. I had couple of problems. I wasn't able to create new account and set account permissions/restrictions (had to do it manually and disable encryption) and there were problems with blades. Some views (registration, home page/dashboard) were missing also. 

I ended up using WP and one of the plugins that enables AJAX frontend booking management. Thanks for reaching out tho. You can close this issue. Have a nice day!
